# Change these first
owner: mewwme # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Mewwme Website
    url: https://meww.me
  - name: Mewwme Docs
    url: https://docs.meww.me
  - name: Mewwme's
    url: http://34.142.204.199:65535
  - name: Mewwme's [1]
    url: http://168.119.88.145:3004
  - name: Mewwme's [2]
    url: http://168.119.88.145:3009

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.meww.me
  baseUrl: /upttime
  logoUrl: https://avatars.githubusercontent.com/u/151395981?s=200&v=4
  name: Mewwme Uptime
  theme: night
  introTitle: "The Discord music bot that's 100% free with no payment or votes required to access all its amazing functionalities."
  introMessage: See which of my websites are up, which are down, and which are broken here!
  navbar:
    - title: Invite bot
      href: https://is-a.fun/mybot
    - title: Official Website
      href: https://meww.me
    - title: Server Support
      href: https://discord.gg/6EXgrmtkPX
      
theme: dark
skipDescriptionUpdate: true
skipTopicsUpdate: true

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "*/5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
